[project]
name = "fastapi-celery-app-docker-compose-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "celery[redis]==5.5.3",
    "fastapi==0.116.1",
    "uvicorn[standard]==0.35.0",
]
